[phases.setup]
aptPkgs = [
	"python3",
	"python3-venv",
	"python3-pip",
	"build-essential",
	"gcc",
	"g++",
	"libssl-dev",
	"libffi-dev"
]

[phases.install]
cmds = [
	"python3 -m venv /opt/venv --copies",
	". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python 'ichimoku live.py'"
stopSignal = "SIGINT"


