[phases.setup]
provider = "python"
aptPkgs = [
    "build-essential",
    "libta-lib0",
    "libta-lib-dev"
]

[phases.install]
cmd = "pip install -r requirements.txt"

[start]
cmd = "python ichimoku\\ live.py"